[theme]
# Primary accent color for interactive elements.
primaryColor = "#00ff7f"  # Spring Green

# Background color for the main content area.
backgroundColor = "#002b36"  # Very dark grey (almost black)

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#333333"  # Dark grey

# Color used for almost all text.
textColor = "#ffffff"  # White

# Font for the entire app
font = "sans serif"
